### ISSUE TITLE
 Could not resolve dependencies for project com.sap.mango:jiraintegration:jar:2.1.0: Failure to find jta:jta:jar:1.0.1

### ISSUE THREAD

**Issue by cgerull** [SAP/solman-fb-jira-addon#1]
I encountered this error during the inital build. I had no Atlassian artefacts in my local repository , so everything was freshly downloaded. Can you update the pom.xml to refer to the latestest supported versions?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:30 min
[INFO] Finished at: 2017-12-07T16:25:43+01:00
[INFO] Final Memory: 20M/242M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jiraintegration: Could not resolve dependencies for project com.sap.mango:jiraintegration:jar:2.1.0: Failure to find jta:jta:jar:1.0.1 in https://maven.atlassian.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of atlassian-public has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by cgerull** [comment]
No response, it seems the project is a as dead as doornail.

**Comment by jonathanbaker7** [comment]
Hello @cgerull 

I noticed your recent comment, and I've opened an internal discussion to find the original creators of this project.  I will do my best to get your issue resolved.  

Regards,
Jonathan

**Comment by cgerull** [comment]
Hello Jonathan,

with the latest fixes and latest Atlassian SDK I'm able to build and deploy. But enabling the pluginleads to this error:
[INFO] [talledLocalContainer] 2018-04-14 00:41:32,157 ThreadPoolAsyncTaskExecutor::Thread 21 ERROR admin 41x170x1 18jc2bk 0:0:0:0:0:0:0:1 /rest/plugins/1.0/com.sap.mango.jiraintegration-key [internal.dependencies.startup.DependencyWaiterApplicationContextExecutor] Unable to create application context for [com.sap.mango.jiraintegration], unsatisfied dependencies: none
[INFO] [talledLocalContainer] java.lang.NoClassDefFoundError: org/apache/olingo/server/api/ODataApplicationException
[INFO] [talledLocalContainer] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[INFO] [talledLocalContainer] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[INFO] [talledLocalContainer] 	at java.lang.Class.getConstructors(Class.java:1651)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractBeanDefinition.getResolvedAutowireMode(AbstractBeanDefinition.java:517)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1044)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
[INFO] [talledLocalContainer] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
[INFO] [talledLocalContainer] 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:60)
[INFO] [talledLocalContainer] 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:325)
[INFO] [talledLocalContainer] 	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
[INFO] [talledLocalContainer] 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:290)
[INFO] [talledLocalContainer] 	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:745)
[INFO] [talledLocalContainer] Caused by: java.lang.ClassNotFoundException: org.apache.olingo.server.api.ODataApplicationException not found by com.sap.mango.jiraintegration [169]
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
[INFO] [talledLocalContainer] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] [talledLocalContainer] 	... 21 more

**Comment by frank747** [comment]
Hello,

to solve the dependency problem you need to get the jta-1.0.1.jar file and install it to your local repository. See the instructions here:
https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
Example:
mvn install:install-file -Dfile=C:\temp\jta-1.0.1.jar -DgroupId=jta -DartifactId=jta -Dversion=1.0.1 -Dpackaging=jar

Afterwards the build should work. 
Once the build is done you will find two jar file in the target directory:
jiraintegration-2.1.0.jar
jiraintegration-2.1.0-jar-with-dependencies.jar

You need to take the jiraintegration-2.1.0-jar-with-dependencies.jar to install it on the Jira systems. Then you should not get these class not found exceptions.

Regards,
Frank
